{% set name = "pycollada" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pycollada/pycollada/archive/v{{ version }}.tar.gz
  sha256: e3c29857a65b3dd9c0375c1074195195fc3dada95d6b5c78d246b005f2e85c93

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - python
    - python-dateutil >=2.2
    - numpy

test:
  imports:
    - collada
    - collada.tests

about:
  home: http://pycollada.readthedocs.org/
  license: BSD
  license_family: BSD
  license_file: COPYING
  summary: python library for reading and writing collada documents
  doc_url: http://pycollada.readthedocs.org/
  dev_url: https://github.com/pycollada/pycollada

extra:
  recipe-maintainers:
    - looooo
