{% set name = "pycollada" %}
{% set version = "0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pycollada/pycollada/archive/v{{ version }}.tar.gz
  sha256: 0ed3d422c2e287c187a6f744ad9db2d3bfef69f72d3666d037f1e01a245f5cbc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - python-dateutil >=2.2
    - numpy

test:
  imports:
    - collada
    - collada.tests

about:
  home: http://pycollada.readthedocs.org/
  license: BSD
  license_family: BSD
  license_file: COPYING
  summary: python library for reading and writing collada documents
  doc_url: http://pycollada.readthedocs.org/
  dev_url: https://github.com/pycollada/pycollada

extra:
  recipe-maintainers:
    - looooo
