{% set name = "pycollada" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pycollada/pycollada/archive/v{{ version }}.tar.gz
  sha256: 4cb3a07fc5feaf27b14e276d3b878799ea1377d7a6a49c1e7d78039399e57ecc

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - python-dateutil >=2.2
    - numpy

test:
  requires:
    - python {{ python_min }}
  imports:
    - collada
    - collada.tests

about:
  home: http://pycollada.readthedocs.org/
  license: BSD
  license_family: BSD
  license_file: COPYING
  summary: python library for reading and writing collada documents
  doc_url: http://pycollada.readthedocs.org/
  dev_url: https://github.com/pycollada/pycollada

extra:
  recipe-maintainers:
    - looooo
